name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: 7H3LaughingMan/github-actions/setup-node@main
        with:
          use-cache: true

      - name: TypeScript CI
        uses: 7H3LaughingMan/github-actions/typescript-ci@main
