name: Update pf2e-types
run-name: Update pf2e-types

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: 7H3LaughingMan/github-actions/repository-dispatch@main
        with:
          token: ${{ secrets.PAT }}
          repository: 7H3LaughingMan/pf2e-types
          event_type: foundry-types
